"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";
import { Activity, Settings2 } from "lucide-react";

const STRATEGIES = {
  s1: { 
    name: "S1: Equal Weight (H=5)", desc: "Baseline model. Long top 20.", 
    metrics: { cagr: 22.63, vol: 17.39, sharpe: 1.26, maxDd: -20.63, turnover: 40.79 }, color: "#9CA3AF", imageUrl: "/charts/chart_cell_109.png", 
    explanation: "The absolute foundation of the QuantMLP alpha engine. At the end of every 5-day cycle (H=5), the neural network ranks the entire NIFTY 100 universe based on its continuous output vector. We immediately buy the Top 20 stocks in an equal-weighted portfolio. While this achieves massive Gross Returns, the naive rotation completely disregards the cost of trading. Because the network changes its mind rapidly, the portfolio suffers from a punishing 40%+ turnover per week. This strategy proves the pure predictive power of the model, but is not realistically tradeable in Indian markets due to friction." 
  },
  s2: { 
    name: "S2: Vol-Targeted Top Decile", desc: "Target 15% volatility dynamically.", 
    metrics: { cagr: 12.48, vol: 19.44, sharpe: 0.70, maxDd: -28.74, turnover: 42.10 }, color: "#FBBF24", imageUrl: "/charts/chart_cell_120.png", 
    explanation: "A mathematical attempt to control the violent drawdowns inherent in raw momentum. Every single day, we calculate the 20-day realized volatility of our Top 20 portfolio. We then dynamically scale our gross market exposure to hit a strict 15% annualized volatility target. If the portfolio is experiencing a 30% vol regime, we mathematically deleverage our capital to 50% cash. Conversely, in low vol environments, we leverage up. While theoretically elegant, in extreme market dislocations, realized vol lags implied risk, causing the model to de-leverage too late and miss the subsequent violent recovery." 
  },
  s3: { 
    name: "S3: Rolling Beta Hedged", desc: "Market-neutral via Nifty 50 shorts.", 
    metrics: { cagr: 15.37, vol: 17.74, sharpe: 0.90, maxDd: -25.36, turnover: 45.00 }, color: "#F59E0B", imageUrl: "/charts/chart_cell_133.png", 
    explanation: "An institutional approach designed to strip out entirely systemic market risk (Beta). For every dollar we put into the Top 20 long portfolio, we dynamically short the NIFTY 50 ETF. The exact ratio of our short book is determined by calculating the 60-day rolling Beta of our long portfolio relative to the benchmark. This creates a theoretically market-neutral posture. However, during fierce bull runs, the short leg aggressively bleeds capital, dragging down the overall CAGR. The Sharpe ratio remains mediocre because true market-neutral strategies struggle against the structural upward drift of Indian equities." 
  },
  s4: { 
    name: "S4: Decile Spread (L/S)", desc: "Long Top 10%, Short Bottom 10%.", 
    metrics: { cagr: 4.89, vol: 18.51, sharpe: 0.35, maxDd: -14.02, turnover: 40.00 }, color: "#9467bd", imageUrl: "/charts/chart_cell_142.png", 
    explanation: "The classic academic asset pricing test. We go 100% Long on the Top Decile (best 10 stocks) and 100% Short on the Bottom Decile (worst 10 stocks). This evaluates the pure cross-sectional discriminatory power of the QuantMLP—if the network is truly learning, the long leg will continuously outperform the short leg. While it proves the alpha exists, the absolute returns are crushed because shorting NIFTY 100 stocks in a secular bull market is a suicide mission structurally. The short leg constantly bleeds alpha generated by the long leg." 
  },
  s4_1: { 
    name: "S4.1: Top-10 Spread (L/S)", desc: "Long Top 10, Short Bottom 10.", 
    metrics: { cagr: 8.22, vol: 17.77, sharpe: 0.53, maxDd: -12.30, turnover: 42.00 }, color: "#8c564b", imageUrl: "/charts/chart_cell_151.png", 
    explanation: "A highly concentrated execution of the Decile Spread. By isolating only the absolute top 10 best and top 10 worst stocks across the entire market, we force the network to bet on its highest conviction signals. The discriminatory power is vastly superior here compared to S4, proving the extreme ends of the network's predictions are highly accurate. However, holding only 10 stocks on each side introduces immense idiosyncratic risk (e.g., a single earnings gap-up on a short position can obliterate a month of gains)." 
  },
  s5: { 
    name: "S5: Meta-Labeled Filter", desc: "LightGBM surrogate vetoes bad trades.", 
    metrics: { cagr: 20.23, vol: 17.57, sharpe: 1.14, maxDd: -24.49, turnover: 30.00 }, color: "#A78BFA", imageUrl: "/charts/chart_cell_160.png", 
    explanation: "A cutting-edge ensemble technique inspired by Marcos Lopez de Prado. We use the QuantMLP as our primary signal generator (the 'Fundamental' model). Then, we train a secondary LightGBM decision tree (the 'Meta' model) not to predict returns, but to predict whether the primary model's trade will be profitable! The LightGBM acts as a risk manager, evaluating the volatility and PCR regime. If the Meta model predicts a trade will fail, it vetoes the QuantMLP and keeps the capital in cash. This dramatically reduces turnover but struggles during sudden regime shifts." 
  },
  s6: { 
    name: "S6: Options Regime Gated", desc: "PCR + OI trend gating.", 
    metrics: { cagr: 8.74, vol: 13.14, sharpe: 0.70, maxDd: -14.03, turnover: 0 }, color: "#F43F5E", imageUrl: "/charts/chart_cell_169.png", 
    explanation: "A deeply defensive derivative-based filter. Equities often decouple from technicals during heavy options expiries. This strategy calculates the daily change in the NIFTY Put-Call Ratio (PCR) and Futures Open Interest (OI). If both metrics signal severe institutional distribution (a bearish derivative regime), the strategy suspends all equity trading entirely and parks 100% of capital in cash. While it flawlessly navigates market crashes, its sensitivity is too high—it spends too much time out of the market, missing the explosive V-shaped recoveries that characterize modern indices." 
  },
  s7: { 
    name: "S7: Convex Optimization", desc: "Markowitz optimization with constraints.", 
    metrics: { cagr: 21.50, vol: 16.43, sharpe: 1.27, maxDd: -19.58, turnover: 30.50 }, color: "#8B5CF6", imageUrl: "/charts/chart_cell_179.png", 
    explanation: "Moving beyond naive Equal Weighting. We feed the QuantMLP's Alpha Scores alongside a 60-day shrunk covariance matrix into a Convex Optimizer (CVXPY). The objective function solves for the exact portfolio weights that maximize the Ex-Ante Sharpe Ratio. We enforce strict position limits (max 10% per stock) to ensure diversification. While mathematically beautiful, the optimizer is highly sensitive to noise in the covariance matrix, resulting in weights that aggressively flip-flop between rebalance periods, causing high turnover without enough excess return to justify the friction." 
  },
  s1_hold: { 
    name: "S1 Tweak: Holding Period", desc: "Impact of H=5, 10, 20 Days.", 
    metrics: { cagr: 24.12, vol: 16.51, sharpe: 1.39, maxDd: -20.63, turnover: 41.40 }, color: "#9CA3AF", imageUrl: "/charts/chart_cell_185.png", 
    explanation: "A rigorous sensitivity analysis on the base model's time horizon. We backtested the exact same top 20 selection logic but forced the portfolio to hold the stocks for 10 days, then 20 days. The results prove the fundamental nature of our Alpha: the predictive edge decays rapidly. The network is capturing short-term, 5-day mean-reversion and momentum anomalies. Forcing a 20-day hold dilutes the signal entirely. This confirms that to extract the alpha, we must operate on a high-frequency (weekly) rebalance schedule." 
  },
  s1_1: { 
    name: "S1.1: Turnover Buffer Rule", desc: "Hold winners longer (15/30 rank buffer).", 
    metrics: { cagr: 21.57, vol: 16.59, sharpe: 1.26, maxDd: -19.38, turnover: 28.05 }, color: "#60A5FA", imageUrl: "/charts/chart_cell_195.png", 
    explanation: "A highly pragmatic solution to the 40% turnover problem observed in S1. Instead of strictly buying Top 20 and selling anything that drops to #21, we introduce an asymmetrical rank buffer. We only deploy new capital when a stock enters the absolute Top 15. However, we refuse to sell it until its rank degrades all the way below #30. This allows our winners to run and prevents the model from endlessly churning stocks that are hovering around the #20/#21 boundary. Turnover collapses from 40% down to 28% instantly." 
  },
  s1_4: { 
    name: "S1.4: Nifty 200-EMA Scaling", desc: "Scales exposure based on index trend.", 
    metrics: { cagr: 20.76, vol: 15.01, sharpe: 1.36, maxDd: -15.20, turnover: 29.10 }, color: "#34D399", imageUrl: "/charts/chart_cell_204.png", 
    explanation: "A macroeconomic trend-following overlay. We calculate the 200-Day Exponential Moving Average (EMA) of the NIFTY benchmark. If the market breaks below this critical structural level, it indicates a severe bear regime. Instead of shorting, the strategy slashes gross market exposure dynamically, holding a heavy cash position. While effective at dampening drawdowns, the 200-EMA is a heavily lagging indicator. By the time it triggers, the worst of the crash has often already occurred." 
  },
  s1_5: { 
    name: "S1.5: MACD Momentum Filter", desc: "Gross metrics before slippage. The chosen main strategy.", 
    metrics: { cagr: 20.75, vol: 12.91, sharpe: 1.53, maxDd: -10.09, turnover: 38.79 }, color: "#38BDF8", imageUrl: "/charts/chart_cell_213.png", 
    explanation: "The ultimate evolution of our regime filtering. Instead of using the lagging 200-EMA, we calculate the MACD (Moving Average Convergence Divergence) on the broader Nifty Index. MACD is highly responsive to momentum shifts. If the MACD signals a contraction (bearish crossover), the strategy immediately deleverages, slashing exposure to just 20% to weather the storm. This hyper-reactive filter successfully protects capital during flash crashes, resulting in the highest Gross Sharpe Ratio (1.53) and lowest Max Drawdown of any strategy tested." 
  },
  s1_5_net: { 
    name: "Champion: S1.5 Tradeable (Net)", desc: "Cost-adjusted at 20 bps slippage per side. Highly realistic.", 
    metrics: { cagr: 18.29, vol: 12.91, sharpe: 1.36, maxDd: -10.40, turnover: 24.12 }, color: "#2563EB", imageUrl: "/charts/chart_cell_237.png", 
    explanation: "The crown jewel of the research phase. This is the exact S1.5 MACD model, but subjected to ruthless, real-world constraints. We combine the MACD Regime Filter with the 15/30 Turnover Buffer. Most importantly, we deduct a punishing 20 basis points (bps) of slippage and frictional cost on every single trade executed. Even after taking these heavy, realistic haircuts, the QuantMLP Alpha Engine survives, delivering a massive 18.29% Net CAGR out-of-sample with an exceptionally smooth 12.9% volatility. This is the model deployed in the live inference pipeline." 
  }
};

export default function StrategyLab() {
  const [activeId, setActiveId] = useState<keyof typeof STRATEGIES>("s1_5_net");
  const strat = STRATEGIES[activeId];

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-700 pb-20">
      <div>
        <h1 className="text-4xl font-extrabold tracking-tight text-gray-900">
          Strategy <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-teal-400">Lab</span>
        </h1>
        <p className="text-lg text-gray-500 mt-2">Static image viewer extracted directly from Jupyter Notebook cell outputs.</p>
      </div>

      <div className="grid lg:grid-cols-[350px_1fr] gap-6">
        
        <div className="space-y-6">
          <div className="card space-y-4">
            <h3 className="font-bold text-gray-900 flex items-center gap-2 border-b border-gray-100 pb-3">
              <Settings2 className="w-5 h-5 text-blue-500" /> Control Panel
            </h3>
            
            <div className="space-y-2 pt-2">
              <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Select Strategy</label>
              <div className="flex flex-col gap-2">
                {(Object.keys(STRATEGIES) as Array<keyof typeof STRATEGIES>).map((k) => (
                  <button
                    key={k}
                    onClick={() => setActiveId(k)}
                    className={cn(
                      "text-left px-4 py-3 rounded-xl text-sm font-semibold transition-all border",
                      activeId === k ? "bg-blue-50 border-blue-200 text-blue-700 shadow-sm" : "bg-white border-gray-200 text-gray-500 hover:border-gray-300 hover:bg-gray-50"
                    )}
                  >
                    <span className="block">{STRATEGIES[k].name}</span>
                    <span className="text-[10px] font-normal opacity-80">{STRATEGIES[k].desc}</span>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className="card p-2 min-h-[500px] flex flex-col justify-start">
          <div className="px-4 py-3 flex items-center justify-between border-b border-gray-100 bg-gray-50/50 rounded-t-xl mb-4">
            <div>
              <h3 className="font-bold text-gray-900 flex items-center gap-2">
                <Activity className="w-5 h-5 text-blue-500" /> Equity Curve (2023-2026 OOS)
              </h3>
            </div>
            <div className="flex items-center gap-2 bg-white border border-gray-200 px-3 py-1 rounded-full text-[10px] font-bold text-gray-500 uppercase tracking-widest shadow-sm">
              Base 100
            </div>
          </div>
          
          <div className="w-full flex justify-center mb-8 px-4">
            <img 
              src={strat.imageUrl} 
              alt={strat.name} 
              className="w-full max-w-4xl h-auto object-contain rounded-xl shadow-sm border border-gray-100" 
            />
          </div>

          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 px-4 pb-4">
            <div className="kpi-card space-y-1">
              <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">CAGR</p>
              <p className="text-3xl font-extrabold text-blue-600">{strat.metrics.cagr.toFixed(2)}%</p>
            </div>
            <div className="kpi-card space-y-1">
              <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Volatility</p>
              <p className="text-3xl font-extrabold text-gray-900">{strat.metrics.vol.toFixed(2)}%</p>
            </div>
            <div className="kpi-card space-y-1">
              <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Sharpe</p>
              <p className="text-3xl font-extrabold text-teal-600">{strat.metrics.sharpe.toFixed(2)}</p>
            </div>
            <div className="kpi-card space-y-1">
              <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Max DD</p>
              <p className="text-3xl font-extrabold text-red-500">{strat.metrics.maxDd.toFixed(2)}%</p>
            </div>
            <div className="kpi-card space-y-1">
              <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Turnover</p>
              <p className="text-3xl font-extrabold text-gray-900">{strat.metrics.turnover.toFixed(2)}%</p>
            </div>
          </div>
          
          <div className="px-4 pb-4 pt-2 flex-grow flex flex-col">
            <div className="card bg-gray-50/50 p-8 border-blue-100 flex-grow shadow-inner h-full">
              <h4 className="text-sm font-bold text-blue-600 uppercase tracking-widest mb-4">Strategy Explanation</h4>
              <p className="text-gray-700 font-medium leading-loose text-lg">{strat.explanation}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
